### ISSUE TITLE
ETA on issuing new API keys?

### ISSUE THREAD

**Issue by tdmalone** [fluxfederation/powershop-api#4]
Hey guys,

Love that you have an API available. Do you have an ETA on when API keys will be issued again?

Thanks!

**Comment by KieranWynn** [comment]
Seconded. Would love to explore this. Last update was 9 months ago.

**Comment by dylanmckay** [comment]
Hey guys,

At the moment we don't plan on opening up our API. The current ("v4") API was not designed for external use, and so we need to spend some time on it before we could.

When we originally disabled the public API, we decided that we would talk to _actual_ developers who want to use it and see what ideas they have, and what they would like to see in it.

What would everybody here like out of the API? We can't start working on it at the moment, but we'd definitely like the feedback for when we look at the problem again in 6-12 months and see where we are.

If you're super interested in opening it up, I'd recommend sending an [email to us](http://www.powershop.co.nz/contact-us/). The more input we get, the more we know it's wanted!

**Comment by tdmalone** [comment]
Oops, apologies for not writing back to this! And thank you for your response.

I'd be especially keen on using the API to keep track of usage spikes etc. I would probably use it to send Slack messages on particular days when usage went high... or even just send a daily usage update on Slack. I think the key thing for me is just having API access to usage data :)

**Comment by purcell** [comment]
Thanks @tdmalone! There's usually a multiple-day delay on half-hourly usage data, at least in NZ, so I'm not sure if that particular application would be practical, but I agree that in general you'd be able to do all sorts of interesting things with that data if you had access to it.

**Comment by tdmalone** [comment]
Yeah I thought there'd be some sort of delay. Still would be cool though :)

I'd probably also use it to remind me to buy power packs at the end of the month, if I hadn't already.

**Comment by sayanghosh123** [comment]
Similar to the great points above, I'd love to have a connector for IFTTT and Microsoft Flow for usage alerts (if a REST API is not an option). As a customer, I think it's mainly the usage data and trends / analytical alerts ("this is what your winter usage") - and also access to the hourly / half-hourly reading which the portal / app doesn't give me.

**Comment by skwashd** [comment]
I am currently working on a personal life stats dashboard. I'd like to include power usage data so I can render graphs and perform comparison and trend analysis.

**Comment by jimmykl** [comment]
Bump. Is anyone still here? 

My needs are simple: a JSON feed of my daily usage in kWh so I can pull it into some Google sheets for budgeting without having to login / open the app and manually enter the data each day.

If a full API is a bit of effort and overhead maybe you could consider exposing some feeds as a starter?

**Comment by jacobludriks** [comment]
id love for this to be opened back up also.

**Comment by ryanseddon** [comment]
Gonna be available anytime soon? Jemena the actual electricity infra owner (in my area) only has a 30min delay in power usage stats, wanted to use the api to keep my usage near real time. Your app is nicer than the csv data jemena supplies so connecting the two would be great.

**Comment by jimmykl** [comment]
I got this back from Powershop support a week ago:

> I have contacted our developers and the news is not good unfortunately.
> 
> The honest answer is that it isn't going to be happening in the coming 6 - 12 months either.
> 
> I don't have a technical reason for you apart from their focus is on other items in the current road map.
> 
> There are technical reasons which make it difficult around the security of data which means it isn't as easy as just letting customers get the data.

:-/

**Comment by skwashd** [comment]
This week on twitter they suggested that [building a scraper would be easy](https://twitter.com/PowershopAus/status/988309039451783168).

**Comment by ryanseddon** [comment]
heh that is exactly my next step to do this, good to see they won't block me for it.

**Comment by skwashd** [comment]
Wait until their design team wants to redo those pages and your stuff breaks.

**Comment by jimmykl** [comment]
Cool I had missed that csv export. And here I was looking at scraping it out of the graph svg!

**Comment by tdmalone** [comment]
You still gotta handle the login flow with a scraper though :(

Although, I understand their reluctance re authentication for an API. It's definitely more than just making the data available. They could, however, use a service such as AWS' API Gateway which takes care of most of the heavy lifting!

**Comment by kuahyeow** [comment]
@ryanseddon @jimmykl Yes, you can download CSV data, for a date range, for your interval data as stated in the tweet - https://twitter.com/PowershopAus/status/988309039451783168.

As for API keys : I will ask around internally to confirm but AFAIK opening a new API is not high on the list of priorities.

**Comment by dylanmckay** [comment]
@ryanseddon 

> Gonna be available anytime soon? Jemena the actual electricity infra owner (in my area) only has a 30min delay in power usage stats, wanted to use the api to keep my usage near real time. Your app is nicer than the csv data jemena supplies so connecting the two would be great.

For what it's worth, it's unlikely that Powershop could provide readings in real-time like you can directly query from Jemena. It depends on the country and metering company, but in NZ we often get half-hourly readings from the market two days after the fact.

A quick look at random Jemena data looks like we currently get Jemena readings in our system at the end of each day about 5 hours after the day ends.

**Comment by ryanseddon** [comment]
@kuahyeow @dylanmckay so I've manged to automate getting my jemena data but I can't seem to automate logging into my powershop dashboard?

I'm using puppeteer but it says login failed even though the credentials are correct e.g. if I paste them from my password manager the puppeteer chromium instance can log in correctly?

```js
const puppeteer = require('puppeteer');
const { PS_USERNAME, PS_PASSWORD } = process.env;

(async() => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();

  await page.goto('https://secure.powershop.com.au/reports/meter_readings');
  await page.type('input#email', PS_USERNAME);
  await page.type('input#password', PS_PASSWORD);
  await page.click('#login_button');
})();
```

 😤 Turns out double quotes in bash will treat $[char] as a variable and replace it.

**Comment by ryanseddon** [comment]
Got something working if anyone is interested https://github.com/ryanseddon/jemena-powershop

**Comment by jimmykl** [comment]
Awesome thanks @ryanseddon! Forking to work with powershop.co.nz

**Comment by skwashd** [comment]
Thanks. I'm a powercor customer. I'll have to see what I can do to get it working with my setup.

**Comment by kuahyeow** [comment]
Hi all,

I have checked in with the people who manages our roadmap. At this stage, it's looking like next year at least. Sorry this is affecting you. I see that Ryan has managed to get something going which is great! 

I will now close this issue as we will not be issuing API Keys anytime soon.
